# Generated by Django 3.0.5 on 2020-04-18 21:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aPost_text', models.TextField(verbose_name='Post')),
                ('nUser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='username')),
            ],
        ),
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oDate', models.DateField(default=datetime.date(2020, 4, 18))),
                ('aAction', models.CharField(choices=[('login', 'login'), ('request', 'request')], max_length=7, verbose_name='action')),
                ('nUser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='username')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aAction', models.CharField(choices=[('like', 'like'), ('unlike', 'unlike')], max_length=6, verbose_name='like/unlike')),
                ('oDate', models.DateField(default=datetime.date(2020, 4, 18))),
                ('nPost_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='social.Post', verbose_name='post')),
                ('nUser_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='username')),
            ],
        ),
    ]
